name: Use Print Name

on:
  workflow_dispatch:

jobs:
  read-config-and-call:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read name from config.yaml
        id: read_name
        run: |
          name_value=$(yq '.name' config.yaml)
          echo "name_value=$name_value" >> $GITHUB_OUTPUT

      - name: Call Reusable Workflow
        uses: Pranjal-1515/Test-Shared/.github/workflows/print-name.yml@main
        with:
          name_value: ${{ steps.read_name.outputs.name_value }}
