name: Use Print Name

on:
  workflow_dispatch:

jobs:
  read-config-and-call:
    runs-on: ubuntu-latest
    outputs:
      name_value: ${{ steps.read_name.outputs.name_value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read name from config.yaml
        id: read_name
        run: |
          name_value=$(yq '.name' config.yaml)
          echo "name_value=$name_value" >> $GITHUB_OUTPUT

  call-reusable:
    needs: read-config-and-call
    uses: Pranjal-1515/Test-Shared/.github/workflows/print-name.yml@main
    with:
      name_value: ${{ needs.read-config-and-call.outputs.name_value }}
